site_name: "Grindleton & Sawley Project Hub"
site_description: "A support site run by volunteers of the Grindleton and Sawley project."
site_url: https://b4rngrindletonsawley.uk

nav:
  - Home: index.md
  - News:
    - news/index.md
  - About: about.md
  - Investing: investing.md
  - Useful Info:
    - Installation: installation.md
    - FAQs: faqs.md
  - Contact Us: contact.md
  - External Links:
    - Our Facebook Page: https://facebook.com/b4rngrindletonsawley
    - B4RN Website: https://b4rn.org.uk/get-b4rn/

theme:
  name: material
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - social
  - blog:
      pagination_per_page: 5
      blog_dir: news
      blog_toc: true
      post_date_format: full
      post_url_date_format: yyyy-MM-dd
      post_url_format: "{date}/{slug}"
      archive_url_date_format: yyyy-MM
      archive_url_format: "archive/{date}"
      archive_date_format: MMMM yyyy
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
         kwds:
           case: lower
      post_slugify_separator: _

extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/b4rngrindletonsawley
      name: Facebook

markdown_extensions:
  - attr_list

copyright: This site is neither operated nor endorsed by B4RN, but our volunteers work closely and are supported by B4RN.
