authors:
  jonathan.thomson:
    name: Jonathan Thomson
    description: Editor
    avatar: https://avatars.githubusercontent.com/u/1013909
  b4rngs:
    name: B4RNGS
    description: Editor
    avatar: https://avatars.githubusercontent.com/u/1013909
